set(vtkIOXML_LOADED 1)
set(vtkIOXML_DEPENDS "vtkIOGeometry;vtkIOXMLParser")
set(vtkIOXML_LIBRARIES "vtkIOXML")
set(vtkIOXML_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.0")
set(vtkIOXML_LIBRARY_DIRS "")
set(vtkIOXML_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkIOXMLHierarchy.txt")

