set(vtkCommonComputationalGeometry_LOADED 1)
set(vtkCommonComputationalGeometry_DEPENDS "vtkCommonDataModel;vtkCommonMath;vtkCommonSystem")
set(vtkCommonComputationalGeometry_LIBRARIES "vtkCommonComputationalGeometry")
set(vtkCommonComputationalGeometry_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.0")
set(vtkCommonComputationalGeometry_LIBRARY_DIRS "")
set(vtkCommonComputationalGeometry_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkCommonComputationalGeometryHierarchy.txt")

